workflows:
  build_ipa:
    name: Build IPA
    environment:
      flutter: dev
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - jaafarnhh@gmail.com
