workflows:
  build:
    name: Build
    environment:
      flutter: stable

jobs:
  build:
    name: Build APK
    script:
      - flutter packages get
      - flutter build apk --release --target-platform android-arm,android-arm64
