workflows:
  build:
   name: iOS IPA Build Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: mac-mini-m1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Xcode
        uses: actions/setup-xcode@v3
        with:
          xcode-version: 14

      - name: Install pods
        run: |
          pod install

      - name: Build IPA
        run: |
          xcodebuild -workspace ios/App.xcworkspace -scheme App -destination "generic/Platform" -sdk "macosx11.3" -configuration "Release" -archive

      - name: Upload IPA to App Store Connect
        uses: apple/upload-to-app-store@v1.1.0
        with:
          token: ${{ secrets.FASTLANE_APP_STORE_CONNECT_UPLOAD_TOKEN }}
          app-id: ${{ secrets.FASTLANE_APP_STORE_CONNECT_APP_ID }}
          file: build/ios/ipa/*.ipa

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
