name: iOS Codemagic Workflow

instance_type: mac_mini_m1

environment:
  groups:
  - ios

vars:
  XCODE_WORKSPACE: "ios/App.xcworkspace"
  XCODE_SCHEME: "App"
  APP_STORE_CONNECT_ISSUER_ID: <app_store_connect_issuer_id>
  APP_STORE_CONNECT_KEY_IDENTIFIER: <app_store_connect_key_identifier>
  APP_STORE_CONNECT_PRIVATE_KEY: <app_store_connect_private_key>

integrations:
  app_store_connect: codemagic

scripts:
  - name: Install cocoapods
    script: |
      pod install

  - name: Build IPA
    script: |
      xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -destination "generic/Platform" -sdk "macosx11.3" -configuration "Release" -archive

artifacts:
  - build/ios/ipa/*.ipa
publishing:
  app_store_connect:
    api_key: $APP_STORE_CONNECT_PRIVATE_KEY
    key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
    issuer_id: $APP_STORE_CONNECT_ISSUER_ID
    app_id: <app_store_connect_app_id>
    automatic_release: true
