workflows:
  version: 2
  build:
    name: Build
    on:
      push:
        branches:
          - main  # Update this to your main branch name
    jobs:
      - build_ios

jobs:
  build_ios:
    name: Build iOS
    environment:
      flutter: stable
    steps:
      - name: Checkout code
        script:
          - git clone https://github.com/$CI_REPOSITORY_OWNER/$CI_REPOSITORY_NAME.git .
          - git checkout $CI_COMMIT_REF_NAME

      - name: Install dependencies
        script:
          - flutter pub get

      - name: Build iOS
        script:
          - flutter build ios --release --no-codesign

      - name: Archive iOS
        script:
          - xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/Runner.xcarchive archive

      - name: Export IPA
        script:
          - xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist export_options.plist -exportPath build
