workflows:
  build:
    name: Build
    environment:
      flutter: stable

jobs:
  build:
    name: Build APK
    script:
      - flutter packages get
      - flutter build apk --release --target-platform android-arm,android-arm64
      name: Android APK Build Workflow
instance_type: mac_mini_m1
max_build_duration: 120

environment:
  groups:
  - android

vars:
  ANDROID_SDK_HOME: /opt/android-sdk-latest
  BUILD_TOOLS_VERSION: 30.0.3

scripts:
  - name: Install Android SDK
    script: |
      curl -o android-sdk.zip https://dl.google.com/android/repository/android-sdk-latest-linux.zip
      unzip android-sdk.zip
      export PATH=${ANDROID_SDK_HOME}/platform-tools:${ANDROID_SDK_HOME}/tools:${PATH}

  - name: Clean and Build APK
    script: |
      cd android
      ./gradlew clean
      ./gradlew assembleDebug

artifacts:
  - build/outputs/apk/debug/app-debug.apk

